language: python
python:
  - "3.7"
# command to install dependencies
install:
  - python setup.py egg_info
  - pip install -r photonai.egg-info/requires.txt
  - pip install tensorflow
# command to run tests
script:
  - PYTHONPATH=./ pytest photonai/test/base_tests
