os: linux
dist: bionic
language: python
python:
  - "3.7"
services:
  - docker
before_install:
  - docker pull mongo:latest
  - docker run -d -p 27017-27019:27017-27019 --name mongodb mongo
install:
  - sudo apt-get update
  - sudo apt-get -y install gfortran swig
  - python setup.py egg_info
  - pip install -r photonai.egg-info/requires.txt
  - pip install -r photonai/optimization/smac/smac_requirements.txt
  - pip install tensorflow
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - PYTHONPATH=./ pytest ./test --cov=./photonai
after_success:
  - coveralls
