os: linux
dist: bionic
language: python
python:
  - "3.7"
# command to install dependencies
serivces:
  - docker
before_install:
  - docker pull mongo:4.0.4
  - docker run -d -p 27017-27019:27017-27019 --name mongodb mongo:4.0.4
install:
  - sudo apt-get update
  - sudo apt-get -y install gfortran swig
  - python setup.py egg_info
  - pip install -r photonai.egg-info/requires.txt
  - pip install -r photonai/optimization/fabolas/fabolas_requirements.txt
  - pip install -r photonai/optimization/smac/smac_requirements.txt
  - pip install tensorflow
  - pip install coveralls
# command to run tests
script:
  - PYTHONPATH=./ pytest photonai/test/
after_success:
  - coveralls
