site_name: ""
docs_dir: documentation/docs
nav:
  - 'Getting Started':
    - Introduction: index.md
    - Classification: classification.md
    - Regression: regression.md
  - 'API':
    - 'Base':
      - Hyperpipe: api/base/hyperpipe.md
      - Architecture: architecture.md
    - 'Optimization':
      - GridSearch: api/optimization/grid_search.md
      - RandomGridSearch: api/optimization/random_grid_search.md
      - TimeBoxedRandom_GS: api/optimization/time_boxed_random_grid_search.md
      - scikit-optimize: api/optimization/skopt.md
      - SMAC: api/optimization/smac.md
      - Nevergrad: api/optimization/nevergrad.md
    - 'Processing':
      - Results Handler: api/processing/not_ready_results_handler.md
  - 'Features':
      - 'Over- /Undersampling': examples/imbalanced_data.md
      - 'Custom Metrics': custom_metrics.md
      - 'Hyperparameter Optimization Shortcuts': performance_constraints.md

  - 'Algorithms':
      'Transformers': transformers.md
      'Estimators': estimators.md
  - 'Examples':
      - 'Sample Pairing': sample_pairing.md
      - 'Over- and Undersampling': over_undersampling.md
  - 'About':
      - 'Contributions': contribution.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: documentation/overrides
  repo_url: https://github.com/wwu-mmll/photonai
  features:
    - navigation.tabs

plugins:
  - search
  - macros:
      include_dir: examples
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_"
              - "^__init__$"
#          setup_commands:
#            - import sys, os
#            - curr_dir = os.path.dirname(__file__)
#            - sys.path.append(os.path.join(curr_dir, "../photonai"))
