site_name: ""
docs_dir: documentation/docs
nav:
  - 'Getting Started':
    - Introduction: index.md
    - Classification: getting_started/classification.md
    - Regression: getting_started/regression.md
    - Saving and loading: getting_started/save_load.md
    - Registry: getting_started/registry.md
    - Output: getting_started/output.md
  - 'API':
    - 'Base':
      - Hyperpipe: api/base/hyperpipe.md
      - Architecture: architecture.md
    - 'Optimization':
      - GridSearch: api/optimization/grid_search.md
      - RandomGridSearch: api/optimization/random_grid_search.md
      - TimeBoxedRandom_GS: api/optimization/time_boxed_random_grid_search.md
      - scikit-optimize: api/optimization/skopt.md
      - SMAC: api/optimization/smac.md
      - Nevergrad: api/optimization/nevergrad.md
    - 'Processing':
      - Results Handler: api/processing/results_handler.md
  - 'Features':
      - 'Hyperparameter Optimization Shortcuts': features/performance_constraints.md
      - 'Over- /Undersampling': examples/imbalanced_data.md
      - 'Custom Metrics': custom_metrics.md
      - 'Subpipelines': examples/subpipelines.md
      - 'Switch': features/switch.md
      - 'Stack': features/stack.md
      - 'Permutation Test': features/permutation_test.md

  - 'Algorithms':
      'Transformers': transformers.md
      'Estimators': estimators.md
  - 'Examples':
      - No Outer CV: examples/no_outer_cv.md
      - Group driven CV split: examples/group_driven_cv_split.md
      - Feature Subset Pipelines: examples/feature_subset_pipelines.md
      - Classifier Ensemble: examples/classifier_ensemble.md
      - Confounder Removal: examples/confounder_removal.md
      - Sample Pairing: examples/sample_pairing.md
      - Permutation Test: examples/permutation_test.md
      - Subpipelines: examples/subpipelines.md
      - Scikit-learn MLP: examples/scikit_learn_mlp.md
      - DNN with multiclass prediction: examples/dnn_multiclass_prediction.md
      - Custom Transformer: examples/custom_transformer.md
      - Custom Estimator: examples/custom_estimator.md
      - Over- and Undersampling: examples/imbalanced_data.md
  - 'About':
      - 'Contributions': contribution.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: documentation/overrides
  repo_url: https://github.com/wwu-mmll/photonai
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - macros:
      include_dir: examples
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_"
              - "^__init__$"
