site_name: ""
docs_dir: documentation/docs
nav:
  - 'Getting Started':
    - Introduction: index.md
    - Classification: classification.md
    - Regression: regression.md
  - 'API':
    - 'Base':
      - Architecture: architecture.md
      - Branch: api/base/branch.md
      - Hyperpipe: api/base/hyperpipe.md
      - PipelineElement: api/base/pipeline_element.md
      - Preprocessing: api/base/preprocessing.md
      - Registry: api/base/registry.md
      - Stack: api/base/stack.md
      - Switch: api/base/switch.md
    - 'Modelwrapper':
      - 'Feature Selection':
        - FClassifSelectPercentile: api/modelwrapper/feature_selection/FClassifSelectPercentile.md
        - FRegressionFilterPValue: api/modelwrapper/feature_selection/FRegressionFilterPValue.md
        - FRegressionSelectPercentile: api/modelwrapper/feature_selection/FRegressionSelectPercentile.md
        - LassoFeatureSelection: api/modelwrapper/feature_selection/LassoFeatureSelection.md
        - ModelSelector: api/modelwrapper/feature_selection/ModelSelector.md
    - 'Optimization':
      - GridSearch: api/optimization/grid_search.md
      - RandomGridSearch: api/optimization/random_grid_search.md
      - TimeBoxedRandom_GS: api/optimization/time_boxed_random_grid_search.md
      - Scikit-Optimize: api/optimization/skopt.md
      - SMAC: api/optimization/smac.md
      - Nevergrad: api/optimization/nevergrad.md
      - 'Hyperparameter':
        - BooleanSwitch: api/optimization/hyperparameter/boolean_switch.md
        - Categorical: api/optimization/hyperparameter/categorical.md
        - FloatRange: api/optimization/hyperparameter/float_range.md
        - IntegerRange: api/optimization/hyperparameter/integer_range.md
    - 'Processing':
      - Results Handler: api/processing/results_handler.md
  - 'Features':
      - 'Over- /Undersampling': examples/imbalanced_data.md
      - 'Custom Metrics': custom_metrics.md
      - 'Hyperparameter Optimization Shortcuts': performance_constraints.md

  - 'Algorithms':
      'Transformers': transformers.md
      'Estimators': estimators.md
  - 'Examples':
      - 'Sample Pairing': sample_pairing.md
      - 'Over- and Undersampling': over_undersampling.md
  - 'About':
      - 'Contributions': contribution.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: documentation/overrides
  repo_url: https://github.com/wwu-mmll/photonai
  features:
    - navigation.tabs

plugins:
  - search
  - macros:
      include_dir: examples
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_"
              - "^__init__$"
#          setup_commands:
#            - import sys, os
#            - curr_dir = os.path.dirname(__file__)
#            - sys.path.append(os.path.join(curr_dir, "../photonai"))
